#ifndef SERVICE_COMM_CMD_H
#define	SERVICE_COMM_CMD_H

enum {
	CMD_REQ_CLUSTER_LIST = -1,
	CMD_RET_CLUSTER_LIST = -2,
	CMD_DISTRIBUTE_CLUSTER_LIST = -3,
	CMD_CLUSTER_HEARTBEAT = -4,
};

#endif // !SERVICE_COMM_CMD_H
